Disabled course list button
michael-mosler/Pius-App-for-Android pull request #31
Opened 2021-01-21 11:10 UTC by Christoph309

Fixed #28

- Set state of `course list button` to `disabled` when user is not logged in
- Set state of `course list button` to `disabled` when not `isUpperGrade`

2021-01-21 11:11 UTC, Th3Ph4nt0m requested changes

2021-01-21 11:11 UTC, Th3Ph4nt0m commented on app/src/main/java/com/rmkrings/fragments/preferences/GeneralPreferencesFragment.java
> +        System.out.println("?????????????????????????????????????????????" + forSelectedGradeVal);
Debugging message should be removed here

2021-01-21 11:11 UTC, Th3Ph4nt0m commented on app/src/main/java/com/rmkrings/fragments/preferences/GeneralPreferencesFragment.java
> +        System.out.println(isAuthenticated + "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
Debugging message should be removed here

2021-01-21 11:15 UTC, Th3Ph4nt0m commented
The state is not updated when switching from `Q2` to `keine`

2021-01-27 22:20 UTC, Th3Ph4nt0m approved these changes
Looks good for me

2021-04-01 16:05 UTC, michael-mosler approved these changes

2021-04-01 16:13 UTC, merged