[WIP] 33 Include email addresses in Staff Popover.
michael-mosler/Pius-App-for-Android pull request #34
Opened 2021-02-11 20:42 UTC by Christoph309

2021-03-16 16:36 UTC, Th3Ph4nt0m requested changes
Just one formal change to the code style, rest LGTM

2021-03-16 16:36 UTC, Th3Ph4nt0m commented on app/src/main/java/com/rmkrings/data/staff/StaffMember.java
> +        boolean isTeacher = fromJSON.optBoolean("isTeacher");
Since the boolean is only used 1 time, it does not need to be stored in a variable.

2021-03-16 16:36 UTC, Th3Ph4nt0m commented on app/src/main/java/com/rmkrings/data/staff/StaffMember.java
> +        }
```suggestion
email = fromJSON.optBoolean("isTeacher") ? fromJSON.getString("email") : null;
```
Can be one-line!

2021-03-17 20:03 UTC, Th3Ph4nt0m approved these changes, later dismissed

2021-04-01 16:11 UTC, michael-mosler requested changes
There are two minor formatting issues.

2021-04-01 16:11 UTC, michael-mosler commented on app/src/main/java/com/rmkrings/data/staff/StaffMember.java
> +email = fromJSON.optBoolean("isTeacher") ? fromJSON.getString("email") : null;
Looks like an indentation mismatch.

2021-04-01 16:11 UTC, michael-mosler commented on app/src/main/java/com/rmkrings/data/staff/StaffDictionary.java
> +
Single blank lines only, please.

2021-04-02 08:13 UTC, Th3Ph4nt0m commented on app/src/main/java/com/rmkrings/layouts/StaffPopover.java
Still duplicated empty line

2021-04-06 06:30 UTC, Th3Ph4nt0m submitted a review, later dismissed
LGTM now

2021-04-08 14:03 UTC, Th3Ph4nt0m approved these changes
Still LGTM, reverted unwanted changes

2021-04-09 08:02 UTC, michael-mosler approved these changes
Will care for merge conflict on modules.xml

2021-04-09 08:09 UTC, merged