[WIP] Changed height of ticker text
michael-mosler/Pius-App-for-Android pull request #39
Opened 2021-03-16 18:31 UTC by Christoph309

2021-03-28 16:08 UTC, Th3Ph4nt0m requested changes
- The whitespace differs at the top and bottom.
- The Dashboard was not taken into account.

2021-04-02 08:30 UTC, Th3Ph4nt0m commented
We should take care of the empty state here for a better UX:

<img src="https://user-images.githubusercontent.com/44142235/113397807-ebca8a00-939d-11eb-845c-db4f49418b4a.png" width=200>

You can read further here: https://www.toptal.com/designers/ux/empty-state-ux-design

2021-04-10 09:11 UTC, michael-mosler approved these changes

2021-04-10 09:12 UTC, michael-mosler commented
We decided to leave it as it is for now as this an issue that becomes visible fort a short period when loading data, only.

2021-04-10 09:12 UTC, merged